version: '2.2'
services:
  node_server:
    image: prendi/fusion_ordering:latest
    ports:
     - "4000:4000"
    environment:
     - MYSQL_USER=root
     - MYSQL_PASSWORD=
     - MYSQL_DATABASE=experiment
     - MYSQL_HOST=mysql
    volumes:
     - ./:/node_server
    depends_on:
     - mysql
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    volumes:
     - ./dev_setup/:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  nginx:
    image: nginx
    depends_on:
     - "node_server"
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./nginx/:/etc/nginx/conf.d/
     - ./ssl/:/ssl/